[package]
name = "photo_organizer"
version = "0.4.0"
authors = ["Andrew Gremlich <andrew.gremlich@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Organize photos in one folder into date-centric folder structure."
homepage = "https://github.com/andrewgremlich/photo-organizer"
readme = "./readme.md"
documentation = "https://github.com/andrewgremlich/photo-organizer/blob/master/readme.md"
repository = "https://github.com/andrewgremlich/photo-organizer"
keywords = ["photo", "organize"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33", features = ["suggestions", "color", "vec_map"] }
glob = "0.3.0"
kamadak-exif = "0.5.4"
mkdirp = "1.0.0"
ffmpeg-next = "4.4.0"
